
//CREATE
export const PORTFOLIO_ITEM_CREATE_REQUEST = "PORTFOLIO_ITEM_CREATE_REQUEST"
export const PORTFOLIO_ITEM_CREATE_SUCCESS = "PORTFOLIO_ITEM_CREATE_SUCCESS"
export const PORTFOLIO_ITEM_CREATE_FAIL = "PORTFOLIO_ITEM_CREATE_FAIL"
export const PORTFOLIO_ITEM_CREATE_RESET = "PORTFOLIO_ITEM_CREATE_RESET"

//READ
export const PORTFOLIO_FETCH_REQUEST = "PORTFOLIO_FETCH_REQUEST"
export const PORTFOLIO_FETCH_SUCCESS = "PORTFOLIO_FETCH_SUCCESS"
export const PORTFOLIO_FETCH_FAIL = "PORTFOLIO_FETCH_FAIL"
//Read by id
export const PORTFOLIO_ITEM_FETCH_REQUEST = "PORTFOLIO_ITEM_FETCH_REQUEST"
export const PORTFOLIO_ITEM_FETCH_SUCCESS = "PORTFOLIO_ITEM_FETCH_SUCCESS"
export const PORTFOLIO_ITEM_FETCH_FAIL = "PORTFOLIO_ITEM_FETCH_FAIL"


//UPDATE
export const PORTFOLIO_ITEM_UPDATE_REQUEST = "PORTFOLIO_ITEM_UPDATE_REQUEST"
export const PORTFOLIO_ITEM_UPDATE_SUCCESS = "PORTFOLIO_ITEM_UPDATE_SUCCESS"
export const PORTFOLIO_ITEM_UPDATE_FAIL = "PORTFOLIO_ITEM_UPDATE_FAIL"
export const PORTFOLIO_ITEM_UPDATE_RESET = "PORTFOLIO_ITEM_UPDATE_RESET"


//DELETE
export const PORTFOLIO_ITEM_DELETE_REQUEST = "PORTFOLIO_ITEM_DELETE_REQUEST"
export const PORTFOLIO_ITEM_DELETE_SUCCESS = "PORTFOLIO_ITEM_DELETE_SUCCESS"
export const PORTFOLIO_ITEM_DELETE_FAIL = "PORTFOLIO_ITEM_DELETE_FAIL"
export const PORTFOLIO_ITEM_DELETE_RESET = "PORTFOLIO_ITEM_DELETE_RESET"
