
//CREATE
export const PROJECT_ITEM_CREATE_REQUEST = "PROJECT_ITEM_CREATE_REQUEST"
export const PROJECT_ITEM_CREATE_SUCCESS = "PROJECT_ITEM_CREATE_SUCCESS"
export const PROJECT_ITEM_CREATE_FAIL = "PROJECT_ITEM_CREATE_FAIL"
export const PROJECT_ITEM_CREATE_RESET = "PROJECT_ITEM_CREATE_RESET"

//READ
export const PROJECT_FETCH_REQUEST = "PROJECT_FETCH_REQUEST"
export const PROJECT_FETCH_SUCCESS = "PROJECT_FETCH_SUCCESS"
export const PROJECT_FETCH_FAIL = "PROJECT_FETCH_FAIL"
//Read by id
export const PROJECT_ITEM_FETCH_REQUEST = "PROJECT_ITEM_FETCH_REQUEST"
export const PROJECT_ITEM_FETCH_SUCCESS = "PROJECT_ITEM_FETCH_SUCCESS"
export const PROJECT_ITEM_FETCH_FAIL = "PROJECT_ITEM_FETCH_FAIL"


//UPDATE
export const PROJECT_ITEM_UPDATE_REQUEST = "PROJECT_ITEM_UPDATE_REQUEST"
export const PROJECT_ITEM_UPDATE_SUCCESS = "PROJECT_ITEM_UPDATE_SUCCESS"
export const PROJECT_ITEM_UPDATE_FAIL = "PROJECT_ITEM_UPDATE_FAIL"
export const PROJECT_ITEM_UPDATE_RESET = "PROJECT_ITEM_UPDATE_RESET"


//DELETE
export const PROJECT_ITEM_DELETE_REQUEST = "PROJECT_ITEM_DELETE_REQUEST"
export const PROJECT_ITEM_DELETE_SUCCESS = "PROJECT_ITEM_DELETE_SUCCESS"
export const PROJECT_ITEM_DELETE_FAIL = "PROJECT_ITEM_DELETE_FAIL"
export const PROJECT_ITEM_DELETE_RESET = "PROJECT_ITEM_DELETE_RESET"
